### ISSUE TITLE
Terms of use contradict the license

### ISSUE THREAD

**Issue by stefnotch** [random-tools/Discord-Backup-Tool-V2#2]
Hi!

Your readme says

> 〢 Terms Of Usage
>
>    Educational purpose only
>    Reselling is forbidden
>    You can use the source code if you keep credits (in embed + in markdown), it has to be open-source

Meanwhile the repository has a (misspelled) license file.
https://github.com/random-tools/Discord-Backup-Tool-V2/blob/main/LISENCE.md
The MIT license allows for commercial use, and for non-open source usage.

**Comment by 002-sans** [comment]
oh okay, I will change it, thanks !

**Comment by stefnotch** [comment]
@002-sans They still contradict each other.

> You can use the source code if you keep credits (in embed + in markdown), it has to be open-source

makes me think that you actually want a different license. May I recommend a ["copyleft" license](https://fr.wikipedia.org/wiki/Copyleft), like the [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/)?

Like most licenses, the GNU GPLv3 also has a section regarding "no liability".
![image](https://github.com/random-tools/Discord-Backup-Tool-V2/assets/10220080/5c9c3445-c828-4afd-8a98-1a72df4f6455)

**Comment by 002-sans** [comment]
tysm ! I will change it !
