### ISSUE TITLE
could someone help me

### ISSUE THREAD

**Issue by BryanAlberts** [random-tools/Discord-Backup-Tool-V2#3]
![image](https://github.com/random-tools/Discord-Backup-Tool-V2/assets/59321692/b111cd99-a5e8-40c7-b124-d25de118f03f)

**Comment by 002-sans** [comment]
don't use a bot token but a user token

**Comment by 002-sans** [comment]
- you must log in to your Discord account
- you must open the dev console (ctrl + shift + i)
- you have to go to the category **Console**
- you have to paste this into the console:
```js
window.webpackChunkdiscord_app.push([[Math.random()], {}, (req) => {for (const m of Object.keys(req.c).map((x) => req.c[x].exports).filter((x) => x)) {if (m.default && m.default.getToken !== undefined) {return copy(m.default.getToken())}if (m.getToken !== undefined) {return copy(m.getToken())}}}]); console.log("%cDone!", "font-size: 50px"); console.log(`%cYou now have your token in the clipboard!`, "font-size: 16px")
```
- you must ctrl + v in the **token** part of the file __config.json__
